name: my workflow
on: [push]

jobs:
  build:
    name: echo hello
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: npm install

      - name: ls
        run: ls -al

      - name: test
        run: npm run test

        # - name: commit
        #   run: |
        #     date > generated.txt
        #     git config user.name github-actions
        #     git config user.email github-actions@github.com
        #     git add .
        #     git commit -m "generated"
        #     git push

      - name: if success
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])

            await github.pulls.createReview({
              ...context.repo,
              body:"성공!! 다음 문제는 https://classroom.github.com/a/NbtIccEI",
              event: "REQUEST_CHANGES"
            })
            await github.pulls.update({
              ...context.repo,
              state: "closed"
            })
          if: success()
